image: docker:stable

services:
  - docker:stable-dind

.base:
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  only:
    - master

bs-platform-4.0.18:
  extends: .base
  variables:
    NAME: "bs-platform"
    VERSION: "4.0.18"
  script:
    - docker build $NAME --no-cache --pull
      -f $NAME/Dockerfile
      -t $DOCKER_USER/$NAME:$VERSION
      -t $DOCKER_USER/$NAME:latest
      --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      --build-arg VCS_REF=$CI_COMMIT_SHA
      --build-arg VERSION=$VERSION
  after_script:
    - docker push $DOCKER_USER/$NAME:$VERSION
    - docker push $DOCKER_USER/$NAME:latest

firebase-tools-6.4.0:
  extends: .base
  variables:
    NAME: firebase-tools
    VERSION: "6.4.0"
  script:
    - docker build $NAME --no-cache --pull
      -f $NAME/Dockerfile
      -t $DOCKER_USER/$NAME:$VERSION
      -t $DOCKER_USER/$NAME:latest
      --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      --build-arg VCS_REF=$CI_COMMIT_SHA
      --build-arg VERSION=$VERSION
  after_script:
    - docker push $DOCKER_USER/$NAME:$VERSION
    - docker push $DOCKER_USER/$NAME:latest
