image: docker:stable

services:
  - docker:stable-dind

.base:
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  script:
    - docker build $CI_JOB_NAME --no-cache --pull -f $CI_JOB_NAME/Dockerfile -t $DOCKER_USER/$CI_JOB_NAME
  after_script:
    - docker push $DOCKER_USER/$CI_JOB_NAME
  only:
    - master

bs-platform-4.0.18:
  extends: .base
  script:
    - export NAME=bs-platform
    - export VERSION=4.0.18
    - docker build $NAME --no-cache --pull \
      -f $NAME/Dockerfile \
      -t $DOCKER_USER/$NAME:$VERSION \
      -t $DOCKER_USER/$NAME:latest \
      --build-arg VERSION=$VERSION \
      --build-arg VCS_REF=$CI_COMMIT_SHA
  after_script:
    - export NAME=bs-platform
    - export VERSION=4.0.18
    - docker push $DOCKER_USER/$NAME:$VERSION
    - docker push $DOCKER_USER/$NAME:latest

firebase-tools-6.3.1:
  extends: .base
  script:
    - export NAME=firebase-tools
    - export VERSION=6.3.1
    - docker build $NAME --no-cache --pull \
      -f $NAME/Dockerfile \
      -t $DOCKER_USER/$NAME:$VERSION \
      -t $DOCKER_USER/$NAME:latest \
      --build-arg VERSION=$VERSION \
      --build-arg VCS_REF=$CI_COMMIT_SHA
  after_script:
    - export NAME=firebase-tools
    - export VERSION=6.3.1
    - docker push $DOCKER_USER/$NAME:$VERSION
    - docker push $DOCKER_USER/$NAME:latest
