image: docker:stable

services:
  - docker:stable-dind

.base:
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker build . --no-cache --pull -f ./firebase-tools -t $DOCKER_USER/$CI_JOB_NAME
    - docker push $DOCKER_USER/$CI_JOB_NAME
  only:
    - master

firebase-tools:
  extends: .base
